spring:
  datasource:
    url: ${DATABASE_URL}
    #jdbc:postgresql://<host>:<port>/<database>
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    jpa:
        properties:
            hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
        hibernate:
            ddl-auto: update