name: Example Workflow with env

on:
  push:
    branches:
      - main

env:
  MY_VAR: my_value

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Environment Variable
        run: echo $MY_VAR
      - name: Print all Variables
        run: export
