name: Docker Image CI

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Build with Maven
      run: |
        cd phase-1
        mvn -B package --file pom.xml
    
    - name: Build the Docker image
      run: |
        cd phase-1
        docker build . --file Dockerfile --tag todolist:$(date +%s)
