name: Full pipeline from scan to image publish

on:
  workflow_dispatch

env:
  REGISTRY: harbor-registry.dyn.fil.e.ipl.pt:80
  IMAGE_NAME: solvit-cicd
  
jobs:
  scan-vulnerabilities:
    runs-on: ubuntu-latest
    steps:
      - name: mock
        run: echo hello world

  build-all-jars:
    needs: scan-vulnerabilities
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Build Auth Service with Maven
      run: |
        cd phase-3
        cd authusers
        mvn -B -Dmaven.test.skip=true package --file pom.xml
        
    - name: Build ToDo Service with Maven
      run: |
        cd phase-3
        cd todolist
        mvn -B -Dmaven.test.skip=true package --file pom.xml
        
    - name: Build Notifications Service with Maven
      run: |
        cd phase-3
        cd notifications
        mvn -B -Dmaven.test.skip=true package --file pom.xml

    - uses: actions/upload-artifact@v3
      with:
        name: authuser-jar
        path: phase-3/authusers/target/authuser-phase2-1.0.0.jar
        if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`
        
    - uses: actions/upload-artifact@v3
      with:
        name: todolist-jar
        path: phase-3/todolist/target/todolist-phase2-1.0.0.jar
        if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`
        
    - uses: actions/upload-artifact@v3
      with:
        name: notifications-jar
        path: phase-3/notifications/target/todolist-phase2-notifications-1.0.0.jar
        if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`
      
  publish-docker-auth:
    needs: build-all-jars
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: authuser-jar
      - name: Copy JAR to target (to match Dockerfile)
        run: |
          mkdir phase-3/authusers/target
          cp authuser-phase2-1.0.0.jar phase-3/authusers/target/
          
      - name: Display structure of downloaded files
        run: ls -R
      
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.HARBOR_USER_NAME }}
          password: ${{ secrets.HARBOR_USER_PWD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/solvit-cicd/auth-test-upload-download
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: phase-3/authusers/.
          file: phase-3/authusers/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          
      #- name: Build Docker image (native)
      #  run: |
      #    cd phase-3/authusers/
      #    docker build -t ${{ env.REGISTRY }}/solvit-cicd/auth-test-upload-download:latest .

      #- name: Push Docker image (native)
      #  run: |
      #    docker push ${{ env.REGISTRY }}/solvit-cicd/auth-test-upload-download:latest
        
      
  publish-docker-todolist:
      needs: build-all-jars
      runs-on: self-hosted
      steps:
        - name: mock
          run: echo hello world
      # TODO  
  
  publish-docker-notifications:
      needs: build-all-jars
      runs-on: self-hosted
      steps:
        - name: mock
          run: echo hello world
      # TODO

