
name: Hello world 
on: [workflow_dispatch]

jobs: 
    hello-world-job: # The type of runner that the job will run on 
        runs-on: [self-hosted,macOS,x64]          
        # Sequence of tasks that will be executed as part of the job 
        steps: 
        # Checks-out the repository 
        - uses: actions/checkout@v3      
        # Runs a single command using the runner shell 
        - name: Run a one-line script 
          run: echo Hello, world!

