jobs: 
    example_matrix: 
        strategy: 
            matrix: 
                version: [10, 12, 14]
                os: [ubuntu-latest, windows-latest]

        steps:
        - name: running for ${{ matrix.jdk }} and ${{ matrix.version }}
          run: echo hello world

      other_job:
        steps:
        - name: other
          run: echo run other job
