name: Package save and restore

on:
  workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Build Auth Service with Maven
      run: |
        cd phase-2
        cd authusers
        mvn -B -Dmaven.test.skip=true package --file pom.xml
        
    - uses: actions/upload-artifact@v3
      with:
        name: authuser-jar
        path: phase-2/authusers/target/authuser-phase2-1.0.0.jar
        
    
