name: Package save and restore

on:
  workflow_dispatch

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  
jobs:
  build-jar:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Build Auth Service with Maven
      run: |
        cd phase-2
        cd authusers
        mvn -B -Dmaven.test.skip=true package --file pom.xml
        
    - uses: actions/upload-artifact@v3
      with:
        name: authuser-jar
        path: phase-2/authusers/target/authuser-phase2-1.0.0.jar
        if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`
      
  publish-docker:
    needs: build-jar
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: authuser-jar
      - name: Copy JAR to target (to match Dockerfile)
        run: |
          mkdir target
          cp authuser-phase2-1.0.0.jar target
      - name: Display structure of downloaded files
        run: ls -R
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}/test-upload-download
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: phase-3/todolist/.
          file: phase-3/todolist/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
    
