name: Java CI with Maven 
on: 
  workflow_dispatch:
  push:
    branches:
      - main
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  
jobs:
  build-auth-service:
    strategy:
      matrix:
        jdk: [17]
        os: [ubuntu-18.04, ubuntu-20.04]

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build Auth Service with Maven
      run: |
        cd phase-3
        cd authusers
        mvn -B package -Dmaven.test.skip=true
        
  build-todo-service:
    strategy:
      matrix:
        jdk: [17]
        os: [ubuntu-18.04, ubuntu-20.04, ubuntu-22.04]
        
    runs-on: ${{ matrix.os }}   
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build Auth Service with Maven
      run: |
        cd phase-3
        cd todolist
        mvn -B package -Dmaven.test.skip=true
    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

  build-notification-service:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build Auth Service with Maven
      run: |
        cd phase-3
        cd notifications
        mvn -B package -Dmaven.test.skip=true

  
