name: Build ToDo List With Test Matrix

on:
  workflow_dispatch:

jobs:
  test_matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdk: [17]
        os: [ubuntu-18.04, ubuntu-20.04]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.jdk }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.jdk }}
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven
        run: |
          cd phase-2/todolist
          mvn -B -DskipTests=true package

  other:
    runs-on: ubuntu-latest
    steps:
       - name: Execute simple command
         run: echo "Hello, world!" 
